apps/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "acconts"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

apps/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.Dashboard.as_view(), name="dashboard"),
]

config/urls.py
"""config URL Configuration """

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("apps.core.urls", namespace="core")),
    path("accounts/", include("apps.accounts.urls", namespace="accounts")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

apps/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = "core/dashboard.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% block head %}
  <head>
    <!-- === Meta === -->
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <!-- === Title === -->
    <title>Djocial | {% block title %}{% endblock title %}</title>
    <!-- === Bulma CSS === -->
    {% block css-content %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    {% block css %}{% endblock css %}
    {% endblock css-content %}
  </head>
  {% endblock head %}

  {% block body %}
  <body>

    <!-- === Content === -->
    {% block content %} {% endblock content %}

  </body>
  {% endblock body %}
</html>

templates/core/dashboard.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}



{% block content %}
<nav class="navbar is-danger" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item is-size-4" href="{% url 'core:dashboard' %}">
        Djocial
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item"> Dashboard </a>
        <a class="navbar-item"> Images </a>
        <a class="navbar-item"> People </a>
      </div>
      <div class="navbar-end">

        <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link"> {{ request.user.username }} </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">Profile</a>
          <hr class="navbar-divider">
          <a href="{% url 'accounts:logout' %}" class="navbar-item">Logged out</a>
        </div>
      </div>

      </div>

      </div>
    </div>
  </div>
</nav>

{% endblock content %}

templates/pages/index.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}



{% block content %}

<nav class="navbar is-danger" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item is-size-4 is-capitalized has-text-light" href="{% url 'core:index' %}">Djocial</a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <a href="{% url 'accounts:logout' %}" class="qa-button-logout button is-danger is-inverted is-outlined">Logout</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>


{% endblock content %}